CREATE TABLE IF NOT EXISTS pembelian_perlengkapan (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    kode VARCHAR(60) NOT NULL,
    tagihan_id INT UNSIGNED NULL,
    siswa_id INT UNSIGNED NOT NULL,
    tahun_ajaran_id INT UNSIGNED NOT NULL,
    item_label VARCHAR(180) NOT NULL,
    jenis ENUM('atribut','seragam','lain') NOT NULL DEFAULT 'lain',
    metode_pembayaran ENUM('cash','tabungan','sekolah') NOT NULL DEFAULT 'cash',
    nominal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    nominal_terbayar DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    sisa_nominal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    status ENUM('menunggu_pembayaran','cicilan_berjalan','lunas','dibatalkan') NOT NULL DEFAULT 'menunggu_pembayaran',
    catatan TEXT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    UNIQUE KEY unique_pembelian_tagihan (tagihan_id),
    UNIQUE KEY unique_pembelian_kode (kode),
    KEY idx_pembelian_status (status),
    KEY idx_pembelian_siswa (siswa_id),
    KEY idx_pembelian_tahun (tahun_ajaran_id),
    CONSTRAINT fk_pembelian_tagihan FOREIGN KEY (tagihan_id) REFERENCES tagihan(id) ON DELETE CASCADE,
    CONSTRAINT fk_pembelian_siswa FOREIGN KEY (siswa_id) REFERENCES siswa(id) ON DELETE CASCADE,
    CONSTRAINT fk_pembelian_tahun FOREIGN KEY (tahun_ajaran_id) REFERENCES tahun_ajaran(id) ON DELETE CASCADE,
    CONSTRAINT fk_pembelian_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_pembelian_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
