CREATE TABLE IF NOT EXISTS `file_manager_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `school_period` varchar(100) NOT NULL,
  `school_year_id` int unsigned DEFAULT NULL,
  `semester` tinyint unsigned DEFAULT NULL,
  `category` varchar(100) NOT NULL,
  `subcategory` varchar(100) NOT NULL,
  `disk` varchar(20) NOT NULL DEFAULT 'public',
  `relative_path` varchar(500) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `original_name` varchar(255) DEFAULT NULL,
  `file_type` varchar(50) NOT NULL DEFAULT 'other',
  `mime_type` varchar(150) DEFAULT NULL,
  `size_bytes` bigint unsigned NOT NULL DEFAULT 0,
  `uploaded_by_user_id` int unsigned DEFAULT NULL,
  `related_type` varchar(100) DEFAULT NULL,
  `related_id` bigint unsigned DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_file_manager_relative_path` (`relative_path`),
  KEY `idx_file_manager_period_category` (`school_period`, `category`, `subcategory`),
  KEY `idx_file_manager_type` (`file_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
